#ifndef STARMASTERTRACKER_PIONEER_DVD_REMOTE_H
#define STARMASTERTRACKER_PIONEER_DVD_REMOTE_H

#define PLAY_BTN 0XC53A7986
#define PAUSE_BTN 0XC53AF906
#define REWIND_BTN 0XC53AB946

#endif //STARMASTERTRACKER_PIONEER_DVD_REMOTE_H
